version: '1'
services:

  #Start SonarQube
  sonarqube:
    image: sonarqube:latest
    container_name: Sonarqube
    environment: 
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_TOKEN=12345
    ports: 
      - '9000:9000'
    networks:
      - net1

  # Start scraper after SonarQube is started so the client is not bugged & broken
  scraper:
    depends_on:
      - sonarqube
    image: scraper:latest
    container_name: scraper
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_SCANNER_OPTS=-Dsonar.projectKey=testing:sonar

    networks:
      - net1
      
networks:
  net1: